#!/bin/bash
set -e;

# Check if name is specified
if [[ $1 == mysqldb:* ]]; then
    if [[ -z $2 ]]; then
        echo
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

# Load master config
source $DOKKU_ROOT/.mysql-configs/master

case "$1" in

  mysqldb:create)
    # Check if an existing DB volume exists
    if [[ -f "$DOKKU_ROOT/.mysql-configs/pwd_$APP" ]]; then
        #VOLUME="`cat $DOKKU_ROOT/.mariadb/volume_$APP`:/opt/mysql"
        echo
        echo "-----> Database config detected for $APP, skipping DB install"
    else
        #VOLUME="/opt/mysql"
        # Generate a random password for DB user
        DB_PASSWORD=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 16)
        echo $DB_PASSWORD > "$DOKKU_ROOT/.mysql-configs/pwd_$APP"
        chown dokku: "$DOKKU_ROOT/.mysql-configs/pwd_$APP"
        chmod 700 "$DOKKU_ROOT/.mysql-configs/pwd_$APP"
        # connect to mySql server and create database if it does not exist.
        RESULT=`mysqlshow --user="$PRIVUSER" --port="$PORT" --password="$PRIVPASS" $APP| grep -v Wildcard | grep -o $APP`
        if [ "$RESULT" == "$APP" ]; then
            # purge old user and update
            mysql --host=HOST --user="$PRIVUSER" --port="$PORT" --password="$PRIVPASS" -e "DROP USER $APP; GRANT ALL PRIVILEGES ON $APP.* to $APP@'%' INDENTIFIED BY '$DB_PASSWORD';";
            echo
            echo "-----> $APP database already exists, updated user for database."
        else
            # add db & set db user/permissions
            mysql --host=HOST --user="$PRIVUSER" --port="$PORT" --password="$PRIVPASS" -e "CREATE DATABASE $APP; GRANT ALL PRIVILEGES ON $APP.* to $APP@'%' INDENTIFIED BY '$DB_PASSWORD';";
            echo
            echo "-----> MySQL Database  created for: $APP"
        fi
        # Link to a potential existing app
        dokku mariadb:link $APP $APP
    fi
    sleep 1
    dokku mysqldb:info $APP
    ;;

  mysqldb:delete)
    # Remove container db password
    if [[ -f "$DOKKU_ROOT/.mysql-configs/pwd_$APP" ]]; then
        rm -f "$DOKKU_ROOT/.mysql-configs/pwd_$APP"
    fi
    
    # Connect to mysql, backup database & delete
    echo
    echo "-----> MySQL database deleted for: $APP"
    ;;
    
  mariadb:link)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $3 ]]; then
        echo "Linking db to $APP"
        DB_IMAGE="mariadb/$APP"
        DB_PASSWORD=$(cat "$DOKKU_ROOT/.mariadb/pwd_$APP")
        PORT=$(cat "$DOKKU_ROOT/.mariadb/port_$APP")
        # Link database using dokku command
        dokku config:set $APP "DATABASE_URL=mysql2://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
        #All DB-variables as ENV
        dokku config:set $APP "DB_HOST=172.17.42.1 DB_PASS=$DB_PASSWORD DB_NAME=db DB_PORT=$PORT DB_USER=root"
        exit 1
    fi
    DB_IMAGE="mariadb/$3"
    if [[ ! -f "$DOKKU_ROOT/.mariadb/pwd_$3" ]]; then
        echo "Database is not initialized correctly"
        exit 1
    fi
    DB_PASSWORD=$(cat "$DOKKU_ROOT/.mariadb/pwd_$3")
    PORT=$(cat "$DOKKU_ROOT/.mariadb/port_$3")
    # Link database using dokku command
    dokku config:set $APP "DATABASE_URL=mysql2://root:$DB_PASSWORD@172.17.42.1:$PORT/db"
    #All DB-variables as ENV
    dokku config:set $APP "DB_HOST=172.17.42.1 DB_PASSWORD=$DB_PASSWORD DB_NAME=db DB_PORT=$PORT DB_USER=root"
    echo
    echo "-----> $APP linked to $DB_IMAGE database"
    
    fi
    ;;

  mysqldb:info)
    echo
    echo "       Host: $HOST"
    echo "       Port: $PORT"
    echo "       User: 'root'"
    echo "       Password: '$(cat "$DOKKU_ROOT/.mariadb/pwd_$APP")'"
    echo "       Database: 'db'"
    echo
    ;;

  mysqldb:console)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $2 ]]; then
            echo "You must specify a database name"
            exit 1
        fi

        DB_PASSWORD=$(cat "$DOKKU_ROOT/.mariadb/pwd_$2")
        # Open database using mysql-client
        mysql --host="$HOST" --user="$2" --port="$PORT" --password="$DB_PASSWORD" $2
    fi
    ;;

  mysqldb:dump)
    if $APP_EXISTS; then
        # Check argument
        if [[ -z $2 ]]; then
            echo "You must specify a database name"
            exit 1
        fi

        DB_PASSWORD=$(cat "$DOKKU_ROOT/.mysql-configs/pwd_$2")
        # Check if user gave a filename
        if [[ -z $3 ]]; then
            echo "Dumping to $2-dump$(date +%s).sql"
            mysqldump --host="$HOST" --user="$2" --port="$PORT" --password="$DB_PASSWORD" $2 > "$2-dump$(date +%s).sql"
            exit 1
        fi
        mysqldump --host="$HOST" --user="$2" --port="$PORT" --password="$DB_PASSWORD" $2 > $3
    fi
    ;;

  help)
    cat && cat<<EOF
    mariadb:create <app>      Create a MariaDB container
    mariadb:delete <app>      Delete specified MariaDB container
    mariadb:info <app>        Display database information
    mariadb:console <app>     Open mysql-console to MariaDB container
    mariadb:dump <app> <file> Dump default db database into file
EOF
    ;;

esac
