#!/bin/bash

# Build docker image
# No install needed, we use external mysql server/cluster :)
# git clone https://github.com/Kloadut/dokku-md-dockerfiles /tmp/dokku-md-dockerfiles
# docker build -q=true -t kloadut/mariadb /tmp/dokku-md-dockerfiles
# rm -rf /tmp/dokku-md-dockerfiles
